version: '3.8'

services:
  face_recon:
    image: node:latest
    container_name: face_recon_container
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: yarn start
